
import __ASTRO_IMAGE_IMPORT_Z59Wqu from "../../../assets/blog/video-formats.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fconvert-video-formats-guide.md";
import __ASTRO_IMAGE_IMPORT_1UH9FL from "../../../assets/blog/transcriber-ai.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fhow-to-transcribe-audio-video-ai.md";
import __ASTRO_IMAGE_IMPORT_Z1OGGcr from "../../../assets/blog/youtube-download.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fhow-to-download-youtube-videos-2026.md";
import __ASTRO_IMAGE_IMPORT_1Qfxno from "../../../assets/blog/welcome-hero.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fwelcome-to-downkingo-blog.md";
import __ASTRO_IMAGE_IMPORT_Zl4XK6 from "../../../assets/blog/open-source-downloaders.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fbest-open-source-video-downloaders.md";
import __ASTRO_IMAGE_IMPORT_Z1GBMS6 from "../../../assets/blog/tiktok-download.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fhow-to-download-tiktok-without-watermark.md";
import __ASTRO_IMAGE_IMPORT_Z2oNjTB from "../../../assets/blog/tiktok-download.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fpt%2Fcomo-baixar-tiktok-sem-marca-dagua.md";
import __ASTRO_IMAGE_IMPORT_ZQHaIE from "../../../assets/blog/welcome-hero.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fpt%2Fbem-vindo-ao-blog-downkingo.md";
import __ASTRO_IMAGE_IMPORT_ZqNzAM from "../../../assets/blog/transcriber-ai.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fpt%2Fcomo-transcrever-audio-video-ia.md";
import __ASTRO_IMAGE_IMPORT_2bf6KC from "../../../assets/blog/youtube-download.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fpt%2Fcomo-baixar-videos-youtube-2026.md";
import __ASTRO_IMAGE_IMPORT_18h1nh from "../../../assets/blog/video-formats.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fpt%2Fguia-converter-formatos-video.md";
import __ASTRO_IMAGE_IMPORT_1hggOs from "../../../assets/blog/open-source-downloaders.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fpt%2Fmelhores-downloaders-video-open-source.md";
export default new Map([["../../../assets/blog/video-formats.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fconvert-video-formats-guide.md", __ASTRO_IMAGE_IMPORT_Z59Wqu], ["../../../assets/blog/transcriber-ai.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fhow-to-transcribe-audio-video-ai.md", __ASTRO_IMAGE_IMPORT_1UH9FL], ["../../../assets/blog/youtube-download.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fhow-to-download-youtube-videos-2026.md", __ASTRO_IMAGE_IMPORT_Z1OGGcr], ["../../../assets/blog/welcome-hero.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fwelcome-to-downkingo-blog.md", __ASTRO_IMAGE_IMPORT_1Qfxno], ["../../../assets/blog/open-source-downloaders.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fbest-open-source-video-downloaders.md", __ASTRO_IMAGE_IMPORT_Zl4XK6], ["../../../assets/blog/tiktok-download.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fhow-to-download-tiktok-without-watermark.md", __ASTRO_IMAGE_IMPORT_Z1GBMS6], ["../../../assets/blog/tiktok-download.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fpt%2Fcomo-baixar-tiktok-sem-marca-dagua.md", __ASTRO_IMAGE_IMPORT_Z2oNjTB], ["../../../assets/blog/welcome-hero.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fpt%2Fbem-vindo-ao-blog-downkingo.md", __ASTRO_IMAGE_IMPORT_ZQHaIE], ["../../../assets/blog/transcriber-ai.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fpt%2Fcomo-transcrever-audio-video-ia.md", __ASTRO_IMAGE_IMPORT_ZqNzAM], ["../../../assets/blog/youtube-download.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fpt%2Fcomo-baixar-videos-youtube-2026.md", __ASTRO_IMAGE_IMPORT_2bf6KC], ["../../../assets/blog/video-formats.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fpt%2Fguia-converter-formatos-video.md", __ASTRO_IMAGE_IMPORT_18h1nh], ["../../../assets/blog/open-source-downloaders.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fpt%2Fmelhores-downloaders-video-open-source.md", __ASTRO_IMAGE_IMPORT_1hggOs]]);
		